export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const CLEAR_SERVER_ERROR = 'CLEAR_SERVER_ERROR';

export const CHOOSE_CATAGORY_SUCCESS = 'CHOOSE_CATAGORY_SUCCESS';
export const CHOOSE_CATAGORY_FAILURE = 'CHOOSE_CATAGORY_FAILURE';
export const REMOVE_CATAGORY_SUCCESS = 'REMOVE_CATAGORY_SUCCESS';
export const REMOVE_CATAGORY_FAILURE = 'REMOVE_CATAGORY_FAILURE';

export const LIKE_DISCOUNT_SUCCESS = 'LIKE_DISCOUNT_SUCCESS';
export const LIKE_DISCOUNT_FAILURE = 'LIKE_DISCOUNT_FAILURE';

export const REMOVE_DISCOUNT_LIKE_SUCCESS = 'REMOVE_DISCOUNT_LIKE_SUCCESS';
export const REMOVE_DISCOUNT_LIKE_FAILURE = 'REMOVE_DISCOUNT_LIKE_FAILURE';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
